<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## 1 Total Recall

| Term       | Brief description |
|------------|-------------------|
| Subsetting | To select         |
| Indexing   | Select a single elment         |
| Slicing    | Select a range of elements                  |
| Masking    | Selecting elements based on a condition                  |

## 2 Show me the ‘odd’ letters

In [ ]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

odd_numbers = np_array_2d[:,0].astype(int)%2 == 1 # Select and cast odd numbers into integers
odd_letters = np_array_2d[odd_numbers, 1] # Select the matching letters
print(odd_letters)

['A' 'C' 'E' 'G' 'I']


## 3 NumPy Masking

In [27]:
import numpy as np

np_array_2d = np.array([
    [66, 50, 57, -1, -1],
    [92, -1, 88, -1, -1],
    [75, -1, -1, 76, -1],
    [-1, 51, 87, -1, -1],
    [71, -1, 67, -1, 69]])

mask_less = (np_array_2d < 50)*-1
mask_more = (np_array_2d > 50)*1
print(mask_less + mask_more)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [1]:
# Changing the original array

import numpy as np

np_array_2d = np.array([
    [66, 50, 57, -1, -1],
    [92, -1, 88, -1, -1],
    [75, -1, -1, 76, -1],
    [-1, 51, 87, -1, -1],
    [71, -1, 67, -1, 69]])

mask_less = (np_array_2d < 50)*-1
mask_more = (np_array_2d > 50)*1
np_array_2d = mask_less + mask_more
print(np_array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
